// World Cup 2026 constants — all 48 teams, groups, FIFA rankings, rivalry pairs

/** Tournament start date */
export const WC_START = new Date('2026-06-11')

/** Group stage ends */
export const WC_GROUP_END = new Date('2026-07-02')

/** Knockout stage starts */
export const WC_KNOCKOUT_START = new Date('2026-07-04')

/** Final */
export const WC_FINAL = new Date('2026-07-19')

// ---------------------------------------------------------------------------
// Teams — ESPN team ID, display name, ISO 3166-1 alpha-2 code, FIFA ranking
// ---------------------------------------------------------------------------
export interface WCTeam {
  id: string
  name: string
  abbrev: string
  iso2: string // for country-flag-icons
  fifaRank: number
  group: string
  color: string
  altColor: string
}

export const WC_TEAMS: WCTeam[] = [
  // Group A
  {
    id: '8',
    name: 'Mexico',
    abbrev: 'MEX',
    iso2: 'MX',
    fifaRank: 16,
    group: 'A',
    color: '006847',
    altColor: 'ce1126',
  },
  {
    id: '3',
    name: 'South Korea',
    abbrev: 'KOR',
    iso2: 'KR',
    fifaRank: 22,
    group: 'A',
    color: 'c60c30',
    altColor: '003478',
  },
  {
    id: '1903',
    name: 'Czechia',
    abbrev: 'CZE',
    iso2: 'CZ',
    fifaRank: 37,
    group: 'A',
    color: 'd7141a',
    altColor: '11457e',
  },
  {
    id: '1903',
    name: 'South Africa',
    abbrev: 'RSA',
    iso2: 'ZA',
    fifaRank: 60,
    group: 'A',
    color: '007a4d',
    altColor: 'ffb612',
  },
  // Group B
  {
    id: '6',
    name: 'Canada',
    abbrev: 'CAN',
    iso2: 'CA',
    fifaRank: 47,
    group: 'B',
    color: 'ff0000',
    altColor: 'ffffff',
  },
  {
    id: '1903',
    name: 'Bosnia-Herzegovina',
    abbrev: 'BIH',
    iso2: 'BA',
    fifaRank: 65,
    group: 'B',
    color: '002395',
    altColor: 'fecb00',
  },
  {
    id: '1903',
    name: 'Switzerland',
    abbrev: 'SUI',
    iso2: 'CH',
    fifaRank: 19,
    group: 'B',
    color: 'ff0000',
    altColor: 'ffffff',
  },
  {
    id: '1903',
    name: 'Qatar',
    abbrev: 'QAT',
    iso2: 'QA',
    fifaRank: 58,
    group: 'B',
    color: '8d1b3d',
    altColor: 'ffffff',
  },
  // Group C
  {
    id: '5',
    name: 'Brazil',
    abbrev: 'BRA',
    iso2: 'BR',
    fifaRank: 5,
    group: 'C',
    color: '009c3b',
    altColor: 'ffdf00',
  },
  {
    id: '1903',
    name: 'Scotland',
    abbrev: 'SCO',
    iso2: 'GB-SCT',
    fifaRank: 39,
    group: 'C',
    color: '003078',
    altColor: 'ffffff',
  },
  {
    id: '1903',
    name: 'Haiti',
    abbrev: 'HAI',
    iso2: 'HT',
    fifaRank: 83,
    group: 'C',
    color: '00209f',
    altColor: 'd21034',
  },
  {
    id: '1903',
    name: 'Morocco',
    abbrev: 'MAR',
    iso2: 'MA',
    fifaRank: 14,
    group: 'C',
    color: 'c1272d',
    altColor: '006233',
  },
  // Group D
  {
    id: '1903',
    name: 'Paraguay',
    abbrev: 'PAR',
    iso2: 'PY',
    fifaRank: 62,
    group: 'D',
    color: 'd52b1e',
    altColor: '0038a8',
  },
  {
    id: '1903',
    name: 'Türkiye',
    abbrev: 'TUR',
    iso2: 'TR',
    fifaRank: 26,
    group: 'D',
    color: 'e30a17',
    altColor: 'ffffff',
  },
  {
    id: '1903',
    name: 'Australia',
    abbrev: 'AUS',
    iso2: 'AU',
    fifaRank: 23,
    group: 'D',
    color: '00843d',
    altColor: 'ffcd00',
  },
  {
    id: '1903',
    name: 'United States',
    abbrev: 'USA',
    iso2: 'US',
    fifaRank: 11,
    group: 'D',
    color: 'b22234',
    altColor: '3c3b6e',
  },
  // Group E
  {
    id: '1903',
    name: 'Ecuador',
    abbrev: 'ECU',
    iso2: 'EC',
    fifaRank: 44,
    group: 'E',
    color: 'ffd100',
    altColor: '003087',
  },
  {
    id: '1903',
    name: 'Germany',
    abbrev: 'GER',
    iso2: 'DE',
    fifaRank: 12,
    group: 'E',
    color: '000000',
    altColor: 'dd0000',
  },
  {
    id: '1903',
    name: 'Ivory Coast',
    abbrev: 'CIV',
    iso2: 'CI',
    fifaRank: 29,
    group: 'E',
    color: 'f77f00',
    altColor: '009a44',
  },
  {
    id: '1903',
    name: 'Curacao',
    abbrev: 'CUW',
    iso2: 'CW',
    fifaRank: 88,
    group: 'E',
    color: '002b7f',
    altColor: 'f9e814',
  },
  // Group F
  {
    id: '1903',
    name: 'Netherlands',
    abbrev: 'NED',
    iso2: 'NL',
    fifaRank: 7,
    group: 'F',
    color: 'ff6600',
    altColor: '003087',
  },
  {
    id: '1903',
    name: 'Sweden',
    abbrev: 'SWE',
    iso2: 'SE',
    fifaRank: 25,
    group: 'F',
    color: '006aa7',
    altColor: 'fecc02',
  },
  {
    id: '1903',
    name: 'Japan',
    abbrev: 'JPN',
    iso2: 'JP',
    fifaRank: 15,
    group: 'F',
    color: 'bc002d',
    altColor: 'ffffff',
  },
  {
    id: '1903',
    name: 'Tunisia',
    abbrev: 'TUN',
    iso2: 'TN',
    fifaRank: 30,
    group: 'F',
    color: 'e70013',
    altColor: 'ffffff',
  },
  // Group G
  {
    id: '1903',
    name: 'Belgium',
    abbrev: 'BEL',
    iso2: 'BE',
    fifaRank: 3,
    group: 'G',
    color: 'ef3340',
    altColor: 'ffd900',
  },
  {
    id: '1903',
    name: 'Iran',
    abbrev: 'IRN',
    iso2: 'IR',
    fifaRank: 21,
    group: 'G',
    color: '239f40',
    altColor: 'da0000',
  },
  {
    id: '1903',
    name: 'Egypt',
    abbrev: 'EGY',
    iso2: 'EG',
    fifaRank: 34,
    group: 'G',
    color: 'ce1126',
    altColor: 'ffffff',
  },
  {
    id: '1903',
    name: 'New Zealand',
    abbrev: 'NZL',
    iso2: 'NZ',
    fifaRank: 97,
    group: 'G',
    color: '00247d',
    altColor: 'cc142b',
  },
  // Group H
  {
    id: '1903',
    name: 'Spain',
    abbrev: 'ESP',
    iso2: 'ES',
    fifaRank: 2,
    group: 'H',
    color: 'aa151b',
    altColor: 'f1bf00',
  },
  {
    id: '1903',
    name: 'Uruguay',
    abbrev: 'URU',
    iso2: 'UY',
    fifaRank: 17,
    group: 'H',
    color: '5aaaa8',
    altColor: 'ffffff',
  },
  {
    id: '1903',
    name: 'Saudi Arabia',
    abbrev: 'KSA',
    iso2: 'SA',
    fifaRank: 56,
    group: 'H',
    color: '006c35',
    altColor: 'ffffff',
  },
  {
    id: '1903',
    name: 'Cape Verde',
    abbrev: 'CPV',
    iso2: 'CV',
    fifaRank: 71,
    group: 'H',
    color: '003893',
    altColor: 'cf2027',
  },
  // Group I
  {
    id: '1903',
    name: 'Norway',
    abbrev: 'NOR',
    iso2: 'NO',
    fifaRank: 20,
    group: 'I',
    color: 'ef2b2d',
    altColor: 'ffffff',
  },
  {
    id: '1903',
    name: 'France',
    abbrev: 'FRA',
    iso2: 'FR',
    fifaRank: 1,
    group: 'I',
    color: '002395',
    altColor: 'ed2939',
  },
  {
    id: '1903',
    name: 'Senegal',
    abbrev: 'SEN',
    iso2: 'SN',
    fifaRank: 18,
    group: 'I',
    color: '00853f',
    altColor: 'fdef42',
  },
  {
    id: '1903',
    name: 'Iraq',
    abbrev: 'IRQ',
    iso2: 'IQ',
    fifaRank: 63,
    group: 'I',
    color: 'ce1126',
    altColor: '007a3d',
  },
  // Group J
  {
    id: '1903',
    name: 'Argentina',
    abbrev: 'ARG',
    iso2: 'AR',
    fifaRank: 4,
    group: 'J',
    color: '74acdf',
    altColor: 'ffffff',
  },
  {
    id: '1903',
    name: 'Austria',
    abbrev: 'AUT',
    iso2: 'AT',
    fifaRank: 24,
    group: 'J',
    color: 'ed2939',
    altColor: 'ffffff',
  },
  {
    id: '1903',
    name: 'Algeria',
    abbrev: 'ALG',
    iso2: 'DZ',
    fifaRank: 35,
    group: 'J',
    color: '006233',
    altColor: 'd21034',
  },
  {
    id: '1903',
    name: 'Jordan',
    abbrev: 'JOR',
    iso2: 'JO',
    fifaRank: 74,
    group: 'J',
    color: '007a3d',
    altColor: 'ce1126',
  },
  // Group K
  {
    id: '1903',
    name: 'Colombia',
    abbrev: 'COL',
    iso2: 'CO',
    fifaRank: 9,
    group: 'K',
    color: 'fcd116',
    altColor: '003087',
  },
  {
    id: '1903',
    name: 'Portugal',
    abbrev: 'POR',
    iso2: 'PT',
    fifaRank: 6,
    group: 'K',
    color: '006600',
    altColor: 'ff0000',
  },
  {
    id: '1903',
    name: 'Uzbekistan',
    abbrev: 'UZB',
    iso2: 'UZ',
    fifaRank: 69,
    group: 'K',
    color: '1eb53a',
    altColor: 'ffffff',
  },
  {
    id: '1903',
    name: 'Congo DR',
    abbrev: 'COD',
    iso2: 'CD',
    fifaRank: 55,
    group: 'K',
    color: '007fff',
    altColor: 'f7d618',
  },
  // Group L
  {
    id: '1903',
    name: 'England',
    abbrev: 'ENG',
    iso2: 'GB-ENG',
    fifaRank: 8,
    group: 'L',
    color: 'ffffff',
    altColor: 'cf081f',
  },
  {
    id: '1903',
    name: 'Croatia',
    abbrev: 'CRO',
    iso2: 'HR',
    fifaRank: 10,
    group: 'L',
    color: 'ff0000',
    altColor: '0000ff',
  },
  {
    id: '1903',
    name: 'Panama',
    abbrev: 'PAN',
    iso2: 'PA',
    fifaRank: 79,
    group: 'L',
    color: 'da121a',
    altColor: '005293',
  },
  {
    id: '1903',
    name: 'Ghana',
    abbrev: 'GHA',
    iso2: 'GH',
    fifaRank: 66,
    group: 'L',
    color: '006b3f',
    altColor: 'fcd116',
  },
]

// Map from ESPN display name → WCTeam for quick lookup
export const TEAM_BY_NAME = new Map<string, WCTeam>(
  WC_TEAMS.map((t) => [t.name, t])
)

// Map from ESPN display name → ISO2 code
export const ISO2_BY_NAME = new Map<string, string>(
  WC_TEAMS.map((t) => [t.name, t.iso2])
)

// Groups A–L
export const WC_GROUPS = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
] as const
export type WCGroup = (typeof WC_GROUPS)[number]

// Classic rivalries — these get a quality bonus
export const RIVALRY_PAIRS: [string, string][] = [
  ['Brazil', 'Argentina'],
  ['England', 'Germany'],
  ['Spain', 'Portugal'],
  ['United States', 'Mexico'],
  ['Netherlands', 'Belgium'],
  ['France', 'Spain'],
  ['France', 'Germany'],
  ['Brazil', 'France'],
  ['Argentina', 'France'],
  ['England', 'France'],
  ['Germany', 'Netherlands'],
  ['Spain', 'Germany'],
  ['Brazil', 'Germany'],
  ['Argentina', 'Germany'],
  ['England', 'Argentina'],
  ['Brazil', 'England'],
  ['Colombia', 'Argentina'],
  ['Uruguay', 'Argentina'],
  ['Uruguay', 'Brazil'],
  ['Mexico', 'United States'],
  ['Japan', 'South Korea'],
  ['Morocco', 'Algeria'],
  ['Senegal', 'Ivory Coast'],
  ['Egypt', 'Morocco'],
]

// ESPN country logo URL helper
export function espnLogoUrl(abbrev: string): string {
  return `https://a.espncdn.com/i/teamlogos/countries/500/${abbrev.toLowerCase()}.png`
}
